// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = {
    config: {
      layoutMode: {
        title: 'Accent color',
        description: 'Choose the accent color used all over the UI.',
        type: 'string',
        "default": 'Cyan',
        "enum": ['Cyan', 'Pink', 'Red', 'Purple']
      }
    },
    activate: function(state) {
      return atom.themes.onDidChangeActiveThemes(function() {
        var Config;
        Config = require('./config');
        return Config.apply();
      });
    }
  };

}).call(this);
